### ISSUE TITLE
Is there a way to hide the arrow in the dropdown?

### ISSUE THREAD

**Issue by DeBass99** [Akryum/floating-vue#923]
I have tried using CSS to hide the arrow from showing but I cannot seem to get it done

**Comment by ggueyraud** [comment]
Yes, you must override `.v-popper__arrow-container` like this:
```css
.v-popper__arrow-container {
  display: none
}
```
Also to remove the padding you'll need to set `:distance="0"`
